// Artwork database
const artworks = [
    {
        id: 1,
        title: "Presencia Latente",
        artist: "Alfredo Cano Briceño",
        year: 2024,
        price: 2000,
        theme: "Surrealista",
        image: "images/artworks/pintura1.webp",
        model3d: "images/models/obra3d1.glb",
        description: "Esta obra materializa la crudeza del luto a través de una rigurosa paleta monocromática de negros profundos y grises grafito que parecen absorber la luz. De esta atmósfera opresiva emerge una figura solitaria cargando el cuerpo inerte de un niño, evocando una versión contemporánea y sombría de la Pietà. La casi nula distinción entre el fondo y la forma simboliza cómo la tragedia se funde con la existencia del portador, volviéndose una carga inseparable y silenciosa. La técnica exige una mirada penetrante para desvelar la escena, obligando al espectador a ser testigo directo del momento exacto en que el dolor se vuelve tangible y el peso físico del cuerpo se transforma en una carga emocional eterna.",
        gallery: [
            // Add up to 3 images/videos here. Examples:
            // "artworkangularpictures/obra1-detail1.jpg",
            // "artworkangularpictures/obra1-detail2.jpg",
            // "artworkangularpictures/obra1-process.mp4"
        ]
    },
    {
        id: 2,
        title: "Saturación Tropical",
        artist: "Alfredo Cano Briceño",
        year: 2023,
        price: 18750,
        theme: "Textual",
        image: "images/artworks/pintura2.webp",
        model3d: "images/models/obra3d2.glb",
        description: "Esta obra deconstruye la imagen idílica del paraíso brasileño, transformando el paisaje de playa en una vorágine de abstracción orgánica. La composición está saturada por una masa caótica de formas que evocan cuerpos entrelazados, carne y vegetación, pintados en tonos viscerales de rosa, rojo, púrpura y verde, y delimitados por líneas que fragmentan la escena como un vitral convulso. Sobre este frenesí visual, la palabra IPANEMA se impone en blanco inmaculado como una marca comercial o una etiqueta turística, generando un contraste crítico entre la promesa aséptica del destino de lujo y la realidad abrumadora, física y sudorosa de la experiencia tropical colectiva.",
        gallery: [
            "images/artworksangularpictures/obra2g.jpg",
        ]
    },
    {
        id: 3,
        title: "Anatomía del Delirio",
        artist: "Alfredo Cano Briceño",
        year: 2024,
        price: 15900,
        theme: "Abstracto",
        image: "images/artworks/pintura3.webp",
        model3d: "images/models/obra3d3.glb",
        description: "Esta composición es un vibrante ejercicio de horror vacui que amalgama la crudeza del arte callejero con la complejidad del abstraccionismo biológico. El lienzo se presenta como un tejido denso de formas orgánicas —que evocan costillas, vértebras y conductos arteriales— ejecutadas en una paleta ácida de rosas neón, azules eléctricos y rojos viscerales. La aplicación de la pintura, con sus goteos y superposiciones caóticas, sugiere un sistema vivo en estado de mutación o un mapa corporal en crisis, creando una tensión hipnótica entre lo grotesco de las entrañas y lo artificial de los colores sintéticos. Es una obra que no ofrece refugio a la mirada, obligando al espectador a perderse en un laberinto frenético que pulsa con una energía vital desbordada.",
        gallery: []
    },
    { id: 4, title: "Convergencia Etérea", artist: "Alfredo Cano Briceño", year: 2024, price: 22000, theme: "Abstracto", image: "images/artworks/pintura4.webp", model3d: "images/models/obra3d4.glb", description: "Esta obra orquesta un diálogo visual entre el caos gestual y la serenidad geométrica. Sobre un fondo convulso de trazos frenéticos en turquesas y verdes oxidados —que evocan una naturaleza salvaje o ruido estático—, flotan grandes formas ovoides translúcidas que parecen desafiar la gravedad. Estas figuras actúan como filtros de calma, superponiéndose para crear nuevas tonalidades a través de veladuras sutiles de ocre y rosa pálido, generando un efecto de profundidad atmosférica. La composición sugiere una búsqueda de orden y claridad en medio de una atmósfera turbulenta, invitando al espectador a contemplar la belleza silenciosa que surge de la intersección entre la materia agitada y la luz inmaterial.", gallery: [] },
    { id: 5, title: "El Mito Suspendido", artist: "Alfredo Cano Briceño", year: 2023, price: 16200, theme: "Surrealista", image: "images/artworks/pintura5.webp", model3d: "images/models/obra3d5.glb", description: "Esta pieza sumerge al espectador en una atmósfera onírica a través de una rigurosa monocromía azul, que congela la escena en un instante de tiempo atemporal y casi clínico. El protagonista, portando el emblema de Superman bajo su ropa como una promesa de fuerza oculta pero quizás inútil, nos confronta con una mirada penetrante mientras sostiene una figura humana diminuta y vulnerable, actuando como un titiritero existencial o un científico en un laboratorio del absurdo. Rodeado de una fauna simbólica —una mantis, una gallina, una rana— que desafía la lógica espacial, la composición teje una narrativa inquietante sobre la identidad y la responsabilidad, cuestionando la noción tradicional del heroísmo para presentarla como un acto de equilibrio extraño, frágil y profundamente melancólico.", gallery: [] },
    { id: 6, title: "Estratos de la Memoria", artist: "Alfredo Cano Briceño", year: 2024, price: 19500, theme: "Abstracto", image: "images/artworks/pintura6.webp", model3d: "images/models/obra3d6.glb", description: "Esta pieza es una inmersión en la abstracción atmosférica, donde el color actúa como el vehículo principal de la emoción. La composición se define por una fuerte dualidad vertical: una masa superior densa y envolvente, dominada por azules índigo, negros carbón y destellos de rojo óxido que sugieren una tormenta interna o un conflicto orgánico, la cual contrasta dramáticamente con la base inferior de tonos crema y blancos rotos que ofrece un espacio de silencio y respiración. Las pinceladas, que oscilan entre el barrido gestual y la mancha difusa, evocan la naturaleza imprecisa del recuerdo, invitando al espectador a descifrar formas que parecen estar en perpetuo estado de formación o disolución dentro de un paisaje psicológico profundo.", gallery: [] },
    { id: 7, title: "Pulso Escarlata", artist: "Alfredo Cano Briceño", year: 2024, price: 14800, theme: "Retrato", image: "images/artworks/pintura7.webp", model3d: "images/models/obra3d7.glb", description: "Esta obra se erige como un estudio vibrante sobre la deconstrucción de la identidad humana. Ejecutada con una paleta monocromática de rojos saturados y bermellones sobre un fondo blanco aséptico, la pieza presenta un rostro que parece estar en pleno proceso de disolución, capturado a través de pinceladas frenéticas y viscerales que denotan urgencia. La pintura prescinde de los detalles anatómicos precisos para favorecer la expresión pura, donde la mancha y el trazo grueso sugieren una psique fragmentada o una emoción desbordada. Es una imagen que vibra con una energía casi sanguínea, desafiando al espectador a reconstruir la fisionomía oculta entre el caos de la materia pictórica.", gallery: [] },
    { id: 8, title: "Midnight Reverie", artist: "Alfredo Cano Briceño", year: 2023, price: 21300, theme: "Textual", image: "images/artworks/pintura8.webp", model3d: "images/models/obra3d8.glb", description: "Esta pieza descompone el retrato tradicional en un rompecabezas de formas orgánicas y celdas cromáticas que evocan una cartografía emocional. Utilizando una paleta de tonos tierra, rosas pálidos, lilas y verdes musgo, el rostro emerge como un paisaje fragmentado, sugiriendo que la identidad no es una superficie sólida, sino una construcción de múltiples estratos. La estructura, que oscila entre el vitral y el camuflaje, envuelve la mirada del sujeto en una atmósfera de melancolía contenida, invitando al espectador a recomponer la figura y a reflexionar sobre cómo la psique humana se oculta y se revela simultáneamente a través de sus propias fracturas.", gallery: [] },
    { id: 9, title: "Identidad Intervenida", artist: "Alfredo Cano Briceño", year: 2024, price: 13900, theme: "Retrato", image: "images/artworks/pintura9.webp", model3d: "images/models/obra3d9.glb", description: "Esta obra presenta un retrato psicológico de alta intensidad donde la figuración lucha por emerger bajo la abstracción gestual. El rostro del sujeto, resuelto en tonos pálidos y violáceos, aparece asediado por una maraña de pinceladas blancas y gruesas que actúan como vendas o tachaduras, sugiriendo un proceso de censura o reescritura de la memoria. Un contorno rojo continuo delimita la cabeza con la precisión de un mapa clínico, aislando la figura del fondo terracota, mientras que un triángulo azul geométrico en la esquina superior introduce una nota de racionalidad discordante. La pieza explora la fragilidad del -yo- contemporáneo, visualizando la lucha interna entre revelarse y protegerse bajo capas de ruido emocional.", gallery: [] },
    { id: 10, title: "Topografía del Silencio", artist: "Alfredo Cano Briceño", year: 2024, price: 17600, theme: "Retrato", image: "images/artworks/pintura10.webp", model3d: "images/models/obra3d10.glb", description: "Esta pieza descompone el retrato tradicional en un rompecabezas de formas orgánicas y celdas cromáticas que evocan una cartografía emocional. Utilizando una paleta de tonos tierra, rosas pálidos, lilas y verdes musgo, el rostro emerge como un paisaje fragmentado, sugiriendo que la identidad no es una superficie sólida, sino una construcción de múltiples estratos. La estructura, que oscila entre el vitral y el camuflaje, envuelve la mirada del sujeto en una atmósfera de melancolía contenida, invitando al espectador a recomponer la figura y a reflexionar sobre cómo la psique humana se oculta y se revela simultáneamente a través de sus propias fracturas.", gallery: [] },
    { id: 11, title: "STopografía del Silencio", artist: "Alfredo Cano Briceño", year: 2023, price: 20100, theme: "Abstracto", image: "images/artworks/pintura11.webp", model3d: "images/models/obra3d11.glb", description: "Susurros de zafiro danzan en el lienzo, creando una atmósfera de serenidad y contemplación profunda.", gallery: [] },
    { id: 12, title: "La Sentencia del Flujo", artist: "Alfredo Cano Briceño", year: 2024, price: 15200, theme: "Textual", image: "images/artworks/pintura12.webp", model3d: "images/models/obra12.glb", description: "Esta pieza articula una poderosa tensión entre el caos material y el orden del destino. Sobre un fondo abisal de negros y violetas profundos, trabajados con una gestualidad frenética y rasgada que roza el vandalismo estético, emergen trazos blancos esqueléticos y goteantes que sugieren una lucha orgánica subterránea. Este tumulto abstracto es silenciado y jerarquizado por la imposición de la frase -EL RÍO SIEMPRE ENCUENTRA SU LUGAR-, estampada en una tipografía azul de estilo industrial o de estarcido. La obra funciona como una metáfora visual de la inevitabilidad, donde la violencia de la textura pictórica se rinde ante una certeza inamovible: sin importar la oscuridad o la turbulencia del recorrido, existe una fuerza natural que siempre reclama su curso.", gallery: [] },
    { id: 13, title: "Erudición Mordaz", artist: "Alfredo Cano Briceño", year: 2024, price: 23500, theme: "Textual", image: "images/artworks/pintura13.webp", model3d: "images/models/obra3d13.glb", description: "Esta obra articula una sátira visual punzante que dialoga con la tradición del Pop Art y el surrealismo de Magritte. Sobre un fondo amarillo de -alerta- industrial, se presenta una manzana verde ejecutada con pinceladas realistas y orgánicas —el símbolo por excelencia del conocimiento académico o la tentación—, la cual es intervenida abruptamente por la palabra -KLUGSCHEIẞER- (término alemán coloquial para -sabelotodo-) en una tipografía estarcida azul. La composición utiliza un minimalismo agresivo y un contraste de colores primarios para subvertir la nobleza del fruto, transformándolo en un emblema del ego intelectual y lanzando una crítica ácida y humorística sobre la pretensión de sabiduría.", gallery: [] },
    { id: 14, title: "La Mirada del Absurdo", artist: "Alfredo Cano Briceño", year: 2023, price: 19800, theme: "Retrato", image: "images/artworks/pintura14.webp", model3d: "images/models/obra3d14.glb", description: "Esta obra se adentra en la neo-figuración grotesca, presentando un retrato que desafía los cánones de la belleza convencional mediante la hipérbole anatómica. Sobre un fondo de trazos grises y caóticos que sugieren una atmósfera opresiva, emerge un rostro de intensidad alucinada, dominado por unos ojos desorbitados que confrontan directamente al espectador y unos labios de un rojo carmesí saturado que oscilan entre la sensualidad teatral y la herida abierta. La pincelada, cruda y empastada, enfatiza la carnalidad y la distorsión, transformando al sujeto en una caricatura psicológica que explora la ansiedad, la locura y la vulnerabilidad desnuda de la condición humana.", gallery: [] },
    { id: 15, title: "Toponimia Espectral", artist: "Alfredo Cano Briceño", year: 2024, price: 16700, theme: "Textual", image: "images/artworks/pintura15.webp", model3d: "images/models/obra3d15.glb", description: "Esta obra articula una dialéctica visual entre lo efímero y lo indeleble. El fondo se presenta como una atmósfera espectral de -blanco sobre blanco-, donde trazos orgánicos y esqueléticos parecen flotar o disolverse como en una neblina de ceniza. Rompiendo este silencio visual, la palabra -PARANGARICUTIRIMICUARO- irrumpe con la contundencia de un sello industrial, ejecutada en tonos tierra y violetas quemados. El artista utiliza este icónico trabalenguas y topónimo mexicano no solo como referencia cultural, sino como un ancla de identidad que resiste a la abstracción, sugiriendo que el lenguaje posee una solidez capaz de sobrevivir incluso cuando el paisaje físico parece desvanecerse en el vacío.", gallery: [] },
    { id: 16, title: "La Retórica del Esfuerzo", artist: "Alfredo Cano Briceño", year: 2024, price: 18900, theme: "Textual", image: "images/artworks/pintura16.webp", model3d: "images/models/obra3d16.glb", description: "Esta obra de arte conceptual utiliza el assemblage para construir una crítica mordaz sobre la clase trabajadora y las expectativas del mercado del arte. El punto focal es un par de huaraches rojos de plástico adheridos al lienzo —objetos cotidianos elevados a la categoría de reliquia—, que dialogan con la repetición mecánica y desvanecida de la frase -TRABAJO DURO-, evocando la monotonía de la labor física. A través de textos que subvierten refranes populares (En pies descalzos no entran moscas) y una declaración final de autodefensa irónica (YA LES DIJE QUE NO SÉ PINTAR), el artista desafía la obsesión académica por la técnica, validando la precariedad y la honestidad brutal como una forma de estética superior.", gallery: [] },
    { id: 17, title: "Estratificación Convulsa", artist: "Alfredo Cano Briceño", year: 2023, price: 21700, theme: "Gestual", image: "images/artworks/pintura17.webp", model3d: "images/models/obra3d17.glb", description: "Esta obra es un despliegue de abstracción vigorosa que explora la densidad de la materia y el conflicto cromático. La composición se construye mediante una maraña de trazos gruesos y sinuosos donde predominan los rojos viscerales, los púrpuras profundos y los marrones tierra, intersecados dramáticamente por acentos de turquesa que oxigenan la escena. La técnica, rica en empastes y goteos verticales, sugiere una estructura biológica o geológica en pleno movimiento, creando un -tejido- visual que atrapa al espectador en una tensión constante entre la calidez orgánica de las formas y la frialdad de los contrastes, evocando un sistema vital que lucha por organizarse dentro del caos.", gallery: [] },
    { id: 18, title: "Limestone Tranquility", artist: "Alfredo Cano Briceño", year: 2024, price: 14500, theme: "Abstracto", image: "images/artworks/pintura18.webp", model3d: "images/models/obra3d18.glb", description: "Tranquilidad calcárea emanando de cada pincelada. Paz solidificada en forma y color.", gallery: [] },
    { id: 19, title: "Amber Glow", artist: "Alfredo Cano Briceño", year: 2024, price: 24200, theme: "Abstracto", image: "images/artworks/pintura20.webp", model3d: "images/models/obra3d20.glb", description: "El resplandor del ámbar atrapa momentos de luz eterna, preservados en pintura y emoción.", gallery: [] },
    { id: 20, title: "Indigo Night", artist: "Alfredo Cano Briceño", year: 2023, price: 17300, theme: "Abstracto", image: "images/artworks/pintura21.webp", model3d: "images/models/obra3d21.glb", description: "La noche índigo despliega su manto misterioso, guardián de secretos y sueños nocturnos.", gallery: [] },
    { id: 21, title: "Chalk Whispers", artist: "Alfredo Cano Briceño", year: 2024, price: 13200, theme: "Abstracto", image: "images/artworks/pintura22.webp", model3d: "images/models/obra3d22.glb", description: "Susurros de tiza sobre lienzo crean una narrativa delicada de fragilidad y fuerza contenida.", gallery: [] },
    { id: 22, title: "Bronze Awakening", artist: "Alfredo Cano Briceño", year: 2024, price: 20800, theme: "Abstracto", image: "images/artworks/pintura23.webp", model3d: "images/models/obra3d23.glb", description: "El despertar en tonos bronce señala el amanecer de una nueva era artística y conceptual.", gallery: [] },
    { id: 23, title: "Navy Contemplation", artist: "Alfredo Cano Briceño", year: 2023, price: 18400, theme: "Abstracto", image: "images/artworks/pintura24.webp", model3d: "images/models/obra3d24.glb", description: "Contemplación profunda en azul marino, donde el pensamiento se sumerge en océanos de posibilidad.", gallery: [] },
    { id: 24, title: "Cream Serenity", artist: "Alfredo Cano Briceño", year: 2024, price: 15800, theme: "Abstracto", image: "images/artworks/pintura25.webp", model3d: "images/models/obra3d25.glb", description: "Serenidad cremosa fluyendo a través de la composición como un río de paz absoluta.", gallery: [] },
    { id: 25, title: "Copper Radiance", artist: "Alfredo Cano Briceño", year: 2024, price: 22600, theme: "Abstracto", image: "images/artworks/pintura26.webp", model3d: "images/models/obra3d26.glb", description: "Radiación cobriza iluminando el espacio con calidez metálica y energía transformadora.", gallery: [] },
    { id: 26, title: "Teal Harmony", artist: "Alfredo Cano Briceño", year: 2023, price: 19200, theme: "Abstracto", image: "images/artworks/pintura27.webp", model3d: "images/models/obra3d27.glb", description: "Armonía en verde azulado, equilibrando la pasión del rojo con la calma del azul.", gallery: [] },
    { id: 27, title: "Bone Simplicity", artist: "Alfredo Cano Briceño", year: 2024, price: 14100, theme: "Abstracto", image: "images/artworks/pintura28.webp", model3d: "images/models/obra3d28.glb", description: "Simplicidad ósea reducida a su esencia más pura. Menos es definitivamente más.", gallery: [] },
    { id: 28, title: "Rust Evolution", artist: "Alfredo Cano Briceño", year: 2024, price: 21400, theme: "Abstracto", image: "images/artworks/pintura29.webp", model3d: "images/models/obra3d29.glb", description: "Evolución oxidada mostrando la belleza en la transformación y el paso inevitable del tiempo.", gallery: [] },
    { id: 29, title: "Prussian Depth", artist: "Alfredo Cano Briceño", year: 2023, price: 23100, theme: "Abstracto", image: "images/artworks/pintura30.webp", model3d: "images/models/obra3d30.glb", description: "Profundidades prusianas revelando capas de significado enterradas en pigmentos históricos.", gallery: [] },
    { id: 30, title: "Linen Breath", artist: "Alfredo Cano Briceño", year: 2024, price: 16400, theme: "Abstracto", image: "images/artworks/pintura31.webp", model3d: "images/models/obra3d31.glb", description: "El aliento del lino capturado en texturas orgánicas que respiran vida y naturalidad.", gallery: [] },
    { id: 31, title: "Sienna Warmth", artist: "Alfredo Cano Briceño", year: 2024, price: 18200, theme: "Abstracto", image: "images/artworks/pintura32.webp", model3d: "images/models/obra3d32.glb", description: "Calidez de siena envolviendo al espectador en un abrazo de tonos terrosos y acogedores.", gallery: [] },
    { id: 32, title: "Denim Blues", artist: "Alfredo Cano Briceño", year: 2023, price: 17900, theme: "Abstracto", image: "images/artworks/pintura33.webp", description: "Blues denim evocando texturas familiares transformadas en expresión artística contemporánea.", gallery: [] },
    { id: 33, title: "Eggshell Peace", artist: "Alfredo Cano Briceño", year: 2024, price: 13800, theme: "Abstracto", image: "images/artworks/pintura34.webp", description: "Paz de cáscara de huevo, frágil pero completa. Una celebración de la vulnerabilidad como fortaleza.", gallery: [] },
    { id: 34, title: "Mahogany Legacy", artist: "Alfredo Cano Briceño", year: 2024, price: 25300, theme: "Abstracto", image: "images/artworks/pintura35.webp", description: "Legado de caoba transmitiendo riqueza histórica y profundidad cultural a través del color.", gallery: [] },
    { id: 35, title: "Ocean Vastness", artist: "Alfredo Cano Briceño", year: 2023, price: 20500, theme: "Abstracto", image: "images/artworks/pintura36.webp", description: "Vastedad oceánica expandiéndose más allá del marco, invitando a la inmersión total.", gallery: [] },
    { id: 36, title: "Canvas Purity", artist: "Alfredo Cano Briceño", year: 2024, price: 14900, theme: "Abstracto", image: "images/artworks/pintura37.webp", description: "Pureza del lienzo preservada y celebrada. El potencial infinito del espacio en blanco.", gallery: [] },
    { id: 37, title: "Clay Origins", artist: "Alfredo Cano Briceño", year: 2024, price: 19600, theme: "Abstracto", image: "images/artworks/pintura38.webp", model3d: "images/models/obra3d38.glb", description: "Orígenes arcillosos recordándonos nuestras raíces primordiales y la conexión con la tierra.", gallery: [] },
    { id: 38, title: "Periwinkle Dream", artist: "Alfredo Cano Briceño", year: 2023, price: 22900, theme: "Abstracto", image: "images/artworks/pintura39.webp", model3d: "images/models/obra3d39.glb", description: "Sueño periwinkle flotando entre la vigilia y el sueño, la realidad y la fantasía.", gallery: [] },
    { id: 39, title: "Porcelain Grace", artist: "Alfredo Cano Briceño", year: 2024, price: 17100, theme: "Abstracto", image: "images/artworks/pintura40.webp", description: "Gracia de porcelana manifestada en formas delicadas y acabados impecables.", gallery: [] },
    { id: 40, title: "Umber Earth", artist: "Alfredo Cano Briceño", year: 2024, price: 21800, theme: "Abstracto", image: "images/artworks/pintura41.webp", description: "Tierra de sombra conectando con las profundidades de nuestro planeta y nuestra historia.", gallery: [] },
    { id: 41, title: "Turquoise Spirit", artist: "Alfredo Cano Briceño", year: 2023, price: 18600, theme: "Abstracto", image: "images/artworks/pintura42.webp", model3d: "images/models/obra3d42.glb", description: "Espíritu turquesa bailando con energía vibrante entre el cielo y el mar.", gallery: [] },
    { id: 42, title: "Ecru Elegance", artist: "Alfredo Cano Briceño", year: 2024, price: 15500, theme: "Abstracto", image: "images/artworks/pintura43.webp", model3d: "images/models/obra3d43.glb", description: "Elegancia ecru definiendo el refinamiento a través de la sutileza y el buen gusto.", gallery: [] },
    { id: 43, title: "Brick Heritage", artist: "Alfredo Cano Briceño", year: 2024, price: 23700, theme: "Abstracto", image: "images/artworks/pintura44.webp", description: "Herencia de ladrillo construyendo puentes entre pasado arquitectónico y futuro artístico.", gallery: [] },
    { id: 44, title: "Aegean Memory", artist: "Alfredo Cano Briceño", year: 2023, price: 19900, theme: "Abstracto", image: "images/artworks/pintura45.webp", model3d: "images/models/obra3d45.glb", description: "Memoria egea cristalizada en tonos que recuerdan costas antiguas y mares eternos.", gallery: [] },
    { id: 45, title: "Muslin Softness", artist: "Alfredo Cano Briceño", year: 2024, price: 14600, theme: "Abstracto", image: "images/artworks/pintura46.webp", description: "Suavidad de muselina traducida al medio pictórico con delicadeza extraordinaria.", gallery: [] },
];

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = artworks;
}
